export const pages = {
  LOGIN: "Login",
  HOME: "Home",
  COLLECTION_OVERVIEW: "CollectionOverview",
  FINANCES_OVERVIEW: "FinancesOverview",
  TEACHER_OVERVIEW: "TeacherOverview",
  STUDENT_OVERVIEW: "StudentOverview",
  COLLECTION_HOME: "CollectionHome",
  EDUCATION_COLLECTION: "EducationCollection",
  OCCUPATION_COLLECTION: "OccupationCollection",
  TITLE_COLLECTION: "TitleCollection",
  TRAIN_COLLECTION: "TrainCollection",
  AUDIT_MANAGE: "AuditManage",
  ALL_FINANCES: "AllFinances",
  ALL_TEACHERS: "AllTeachers",
  TEACHER_MANAGE: "TeacherManage",
  ALL_STUDENTS: "AllStudents",
  STUDENT_VIEW: "StudentView",
  EDUCATION_UPDATE: "EducationUpdate",
  OCCUPATION_UPDATE: "OccupationUpdate",
  TITLE_UPDATE: "TitleUpdate",
  TRAIN_UPDATE: "TrainUpdate",
  RECEIPT_UPLOAD: "ReceiptUpload",
  ALL_PERFORMANCES: "AllPerformances",
  PERSONAL_PERFORMANCES: "PersonalPerformance",
};
